name: Deploy Lockstacks

on:
  push:
    branches:
      - main
      - feat/migrate-gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish test coverage report
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: production
          folder: dist
